apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  labels:
    app: keycloak
type: Opaque
stringData:
  KC_DB_USERNAME: admin
  KC_DB_PASSWORD: secret
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: secret
