apiVersion: v1
data:
  CLIENT_URL: http://localhost:3004
  DB_HOST: postgres
  DB_NAME: quizzapp
  DB_PASS: secret
  DB_PORT: "5432"
  DB_USER: admin
  FRONTEND_URL: http://localhost:3000
  GOOGLE_CALLBACK_URL: http://localhost:3000/api/auth/google/callback
  GOOGLE_CLIENT_ID: 87305733081-vf2793p0ccivuvu6q024r84jaeosa6s8.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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
  JWT_SECRET: 7bc58ec1f312959a68a3f82d8ba242fa3bdb4dcae4ca8509b3d64cf3b9812dc516afb2fbb1a915b715b7e8faa10ecaf45b29a0c0b80241e31a1a9922a3903dd52b97d740c6a6e32c70398bec89f7e96bfaf8617edaf312f1ee4e0d19380c908f
  MONGO_URI: mongodb://mongo:27017/session
  PORT: "3004"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  SMTP_EMAIL: project.thousand.123@gmail.com
  SMTP_PASSWORD: vita noro xrjs flfm
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: user-user-service--env
  name: user-service--env
